version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:minseunk
    env_file: .env
    volumes: 
      - mariadb_data:/var/lib/mysql
    networks:
      -  ictnet
    expose:
      - "3306"
    restart: always
    init : true
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:minseunk
    env_file: .env
    depends_on:
      - wordpress
    volumes: 
      - wordpress_data:/var/www/wordpress
    networks:
      -  ictnet
    ports:
      - "443:443"
    restart: always
    init : true
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:minseunk
    env_file: .env
    depends_on:
      - mariadb
    volumes: 
      - wordpress_data:/var/www/wordpress
    networks:
      - ictnet
    expose: 
      - "9000"
    restart: always
    init : true

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/minseunk/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/minseunk/data/mariadb
      o: bind

networks:
  ictnet:
    driver: bridge